[build-system]
build-backend = 'setuptools.build_meta'
requires = ['setuptools>=61.2']

[project]
name = 'torch-spots'
description = 'Deep learning for super-resolution spot detection and decoding'
readme = 'README.md'
requires-python = '>=3.10'
dynamic = ['version']
keywords = [
    'spot detection',
    'single-molecule imaging',
    'multiplexed',
    'deep learning',
    'torch',
    'pytorch',
]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'License :: Apache Version 2',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Scientific/Engineering :: Single-cell Imaging',
    'Topic :: Scientific/Engineering :: Microscopy',
    'Topic :: Scientific/Engineering :: Deep Learning',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'Topic :: Scientific/Engineering :: Image Analysis',
]
dependencies = [
    "deepcell_auth@git+https://github.com/vanvalenlab/deepcell-auth.git",
    "ipython",
    "matplotlib",
    "opencv-python-headless",
    "pyro-ppl",
    "scikit-image",
    "scipy",
    "torch",
    "torchvision",
    "tqdm",
    "zarr",
    "click",
    "pandas"
]

[[project.authors]]
name = 'Van Valen Lab'
email = 'vanvalenlab@gmail.com'

[[project.maintainers]]
name = 'Van Valen Lab'
email = 'vanvalenlab@gmail.com'

[project.urls]
# Homepage = 
"Bug Tracker" = 'https://github.com/vanvalenlab/torch-spots/issues'
# Documentation =
"Source Code" = 'https://github.com/vanvalenlab/torch-spots'

[project.optional-dependencies]
eval = [
    "deepcell-toolbox"
]
test = [
    "pytest"
]

[tool.setuptools]
packages = [
    "torch_spots"
]
platforms = [
    'Linux',
    'Mac OSX',
    'Windows',
    'Unix',
]

[tool.setuptools.dynamic.version]
attr = 'torch_spots.__version__'

# [tool.setuptools.package-data]
# torch_spots = ['tests/*.py']

[tool.ruff]
line-length = 110
target-version="py310"

[tool.ruff.lint]
exclude = ["*.ipynb"]
select = ["E", "F", "UP"]